trigger: none

pool:
  name: Azure Pipelines
  demands:
    - Agent.Name -equals Hosted Agent

steps:

# Install Node.js
- task: Bash@2
  displayName: "Check Node.js version"
  inputs:
    targetType: inline
    script: |
      node --version
      npm --version

# Install Docker
- task: Bash@2
  displayName: "Install Docker"
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce
      sudo usermod -aG docker $(whoami)
      docker --version

# Install Python and pip
- task: Bash@2
  displayName: "Install Python and pip"
  inputs:
    targetType: inline
    script: |
      sudo apt-get install -y python3 python3-pip
      python3 --version
      pip3 --version

# Install Ansible
- task: Bash@2
  displayName: "Install Ansible"
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible
      ansible --version
