
name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceBranchName)

trigger: 
  branches: 
    include: 
      - dummy_main

variables: 
  - group: wellfedbackend-variablegroup

parameters: 
  - name: version 
    displayName: Version 
    type: string 
    default: 'latest'

jobs:
  - job: Wellfed_backend_CD_pipeline
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          echo "Version: $(version)"
          VERSION=$(version)
          echo "VERSION: $VERSION"
        displayName: "Debug Version Parameter"

      - task: Bash@3
        displayName: "Run Ansible Playbook"
        inputs:
          targetType: 'inline'
          script: |
            set -e  # Exit on error
            echo "Current Directory:"
            pwd
            VERSION=$(version)
            echo "VERSION: $VERSION"  # Debug version parameter
            cd $(Build.SourcesDirectory)/aksCluster
            echo "Current Directory after changing:"
            pwd
            echo "Directory Listing:"
            ls -lrt
            echo "Running Ansible Playbook:"
            ansible-playbook ../cicd/ansible/cd.yaml -i "localhost," -e version=$VERSION -v
        env:
          git_username: "$(git_username)"
          git_password: "$(git_password)"
          subscription_id: "$(subscription_id)"
          service_principal_id: "$(service_principal_id)"
          service_principal_secret: "$(service_principal_secret)"
          acr_registry_url: "$(acr_registry_url)"
          acr_username: "$(acr_username)"
          tenant_id: "$(tenant_id)"
          service_name: "$(service_name)"
          source_dir: "$(Build.SourcesDirectory)"
          aks_cluster: "$(aks_cluster)"
          resource_group: "$(resource_group)"
          version: "$(version)"
