
name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceBranchName)

trigger: none

pr: none

variables: 
  - group: wellfedbackend-variablegroup

jobs:
  - job: Wellfed_backend_CI_pipeline
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Bash@3
        displayName: "Run Ansible Playbook"
        env:
          git_username: "$(git_username)"
          git_password: "$(git_password)"
          subscription_id: "$(subscription_id)"
          service_principal_id: "$(service_principal_id)"
          service_principal_secret: "$(service_principal_secret)"
          acr_registry_url: "$(acr_registry_url)"
          acr_username: "$(acr_username)"
          tenant_id: "$(tenant_id)"
          service_name: "$(service_name)"
          source_dir: "$(Build.SourcesDirectory)"
        inputs:
          targetType: inline
          script: |
            pwd
            python3 --version
            pip --version
            pip3 --version
            ls -lrt
            ansible-playbook $(Build.SourcesDirectory)/cicd/ansible/ci.yaml -i "localhost," -v
