apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellfed-deploy
  namespace: wellfed-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: wellfeddev.azurecr.io/backend:latest
        ports:
        - containerPort: 3001
