apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellfed-deploy
  namespace: wellfed-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: wellfed-backend
        image: wellfeddev.azurecr.io/wellfed-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: acr-secret
