apiVersion: v1
kind: Service
metadata:
  name: wellfed-service
  namespace: wellfed-backend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" # Internal Load Balancer
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer