apiVersion: v1
kind: Service
metadata:
  name: wellfed-service
  namespace: wellfed-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP # Internal service type for in-cluster communication
