apiVersion: v1
kind: Service
metadata:
  name: wellfed-service
  namespace: wellfed-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80            # The port that will be accessible externally
      targetPort: 3001    # The port the backend is actually listening on
  type: LoadBalancer     # Exposing the service via LoadBalancer
